version: "3"

services:
  my-loki:
    image: grafana/loki:3.0.0
    container_name: loki-container
    volumes:
      - /home/ubuntu/monitoring-logging-server/loki:/etc/loki
    ports:
      - "3100:3100"
    command:
      - "--config.file=/etc/loki/loki-config.yaml"
    restart: unless-stopped
