version: "3"

services:
  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    volumes:
      - $HOME/prometheus:/etc/prometheus
      - prom_data:/prometheus

volumes:
  prom_data:
