version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: mygrafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}
